"""
Official WC 2026 fixture list — single source of truth for both the UI and the seed script.

Tuple columns:
  (match_num, date_str, time_est, time_local, matchup, group, round_label, venue, city)

date_str    : "DD-Mon-YY" — parseable with strptime("%d-%b-%y")
round_label : display name used in the UI
group       : "" for knockout rounds
matchup     : "Home v Away" for group stage; descriptive placeholder for knockouts
"""

# Maps UI round labels to the stage values stored in the DB fixtures table.
DB_STAGE = {
    "Group Stage":    "Group Stage",
    "Round of 32":    "R32",
    "Round of 16":    "R16",
    "Quarter-finals": "Quarter-finals",
    "Semi-finals":    "Semi-finals",
    "Third Place":    "Third Place",
    "Final":          "Final",
}

FIXTURES: list[tuple] = [
    # ── Group Stage ──────────────────────────────────────────────────────────
    (1,  "11-Jun-26", "15:00", "13:00", "Mexico v South Africa",                        "A", "Group Stage",    "Estadio Azteca",              "Mexico City"),
    (2,  "11-Jun-26", "22:00", "20:00", "South Korea v Czechia",                        "A", "Group Stage",    "Estadio Akron",               "Guadalajara"),
    (3,  "12-Jun-26", "15:00", "15:00", "Canada v Bosnia and Herzegovina",              "B", "Group Stage",    "BMO Field",                   "Toronto"),
    (4,  "12-Jun-26", "21:00", "18:00", "USA v Paraguay",                               "D", "Group Stage",    "SoFi Stadium",                "Los Angeles"),
    (5,  "13-Jun-26", "21:00", "21:00", "Haiti v Scotland",                             "C", "Group Stage",    "Gillette Stadium",            "Boston"),
    (6,  "13-Jun-26", "00:00", "21:00", "Australia v Türkiye",                          "D", "Group Stage",    "BC Place",                    "Vancouver"),
    (7,  "13-Jun-26", "18:00", "18:00", "Brazil v Morocco",                             "C", "Group Stage",    "MetLife Stadium",             "New York/New Jersey"),
    (8,  "13-Jun-26", "15:00", "12:00", "Qatar v Switzerland",                          "B", "Group Stage",    "Levi's Stadium",              "San Francisco Bay Area"),
    (9,  "14-Jun-26", "19:00", "19:00", "Ivory Coast v Ecuador",                        "E", "Group Stage",    "Lincoln Financial Field",     "Philadelphia"),
    (10, "14-Jun-26", "13:00", "12:00", "Germany v Curaçao",                            "E", "Group Stage",    "NRG Stadium",                 "Houston"),
    (11, "14-Jun-26", "16:00", "15:00", "Netherlands v Japan",                          "F", "Group Stage",    "AT&T Stadium",                "Dallas"),
    (12, "14-Jun-26", "22:00", "20:00", "Sweden v Tunisia",                             "F", "Group Stage",    "Estadio BBVA",                "Monterrey"),
    (13, "15-Jun-26", "18:00", "18:00", "Saudi Arabia v Uruguay",                       "H", "Group Stage",    "Hard Rock Stadium",           "Miami"),
    (14, "15-Jun-26", "12:00", "12:00", "Spain v Cape Verde",                           "H", "Group Stage",    "Mercedes-Benz Stadium",       "Atlanta"),
    (15, "15-Jun-26", "21:00", "18:00", "Iran v New Zealand",                           "G", "Group Stage",    "SoFi Stadium",                "Los Angeles"),
    (16, "15-Jun-26", "15:00", "12:00", "Belgium v Egypt",                              "G", "Group Stage",    "Lumen Field",                 "Seattle"),
    (17, "16-Jun-26", "15:00", "15:00", "France v Senegal",                             "I", "Group Stage",    "MetLife Stadium",             "New York/New Jersey"),
    (18, "16-Jun-26", "18:00", "18:00", "Iraq v Norway",                                "I", "Group Stage",    "Gillette Stadium",            "Boston"),
    (19, "16-Jun-26", "21:00", "20:00", "Argentina v Algeria",                          "J", "Group Stage",    "Arrowhead Stadium",           "Kansas City"),
    (20, "16-Jun-26", "00:00", "21:00", "Austria v Jordan",                             "J", "Group Stage",    "Levi's Stadium",              "San Francisco Bay Area"),
    (21, "17-Jun-26", "19:00", "19:00", "Ghana v Panama",                               "L", "Group Stage",    "BMO Field",                   "Toronto"),
    (22, "17-Jun-26", "16:00", "15:00", "England v Croatia",                            "L", "Group Stage",    "AT&T Stadium",                "Dallas"),
    (23, "17-Jun-26", "13:00", "12:00", "Portugal v Congo DR",                          "K", "Group Stage",    "NRG Stadium",                 "Houston"),
    (24, "17-Jun-26", "22:00", "20:00", "Uzbekistan v Colombia",                        "K", "Group Stage",    "Estadio Azteca",              "Mexico City"),
    (25, "18-Jun-26", "12:00", "12:00", "Czechia v South Africa",                       "A", "Group Stage",    "Mercedes-Benz Stadium",       "Atlanta"),
    (26, "18-Jun-26", "15:00", "12:00", "Switzerland v Bosnia and Herzegovina",         "B", "Group Stage",    "SoFi Stadium",                "Los Angeles"),
    (27, "18-Jun-26", "18:00", "15:00", "Canada v Qatar",                               "B", "Group Stage",    "BC Place",                    "Vancouver"),
    (28, "18-Jun-26", "21:00", "19:00", "Mexico v South Korea",                         "A", "Group Stage",    "Estadio Akron",               "Guadalajara"),
    (29, "19-Jun-26", "21:00", "21:00", "Brazil v Haiti",                               "C", "Group Stage",    "Lincoln Financial Field",     "Philadelphia"),
    (30, "19-Jun-26", "18:00", "18:00", "Scotland v Morocco",                           "C", "Group Stage",    "Gillette Stadium",            "Boston"),
    (31, "19-Jun-26", "23:00", "20:00", "Türkiye v Paraguay",                           "D", "Group Stage",    "Levi's Stadium",              "San Francisco Bay Area"),
    (32, "19-Jun-26", "15:00", "12:00", "USA v Australia",                              "D", "Group Stage",    "Lumen Field",                 "Seattle"),
    (33, "20-Jun-26", "16:00", "16:00", "Germany v Ivory Coast",                        "E", "Group Stage",    "BMO Field",                   "Toronto"),
    (34, "20-Jun-26", "20:00", "19:00", "Ecuador v Curaçao",                            "E", "Group Stage",    "Arrowhead Stadium",           "Kansas City"),
    (35, "20-Jun-26", "13:00", "12:00", "Netherlands v Sweden",                         "F", "Group Stage",    "NRG Stadium",                 "Houston"),
    (36, "20-Jun-26", "00:00", "22:00", "Tunisia v Japan",                              "F", "Group Stage",    "Estadio BBVA",                "Monterrey"),
    (37, "21-Jun-26", "18:00", "18:00", "Uruguay v Cape Verde",                         "H", "Group Stage",    "Hard Rock Stadium",           "Miami"),
    (38, "21-Jun-26", "12:00", "12:00", "Spain v Saudi Arabia",                         "H", "Group Stage",    "Mercedes-Benz Stadium",       "Atlanta"),
    (39, "21-Jun-26", "15:00", "12:00", "Belgium v Iran",                               "G", "Group Stage",    "SoFi Stadium",                "Los Angeles"),
    (40, "21-Jun-26", "21:00", "18:00", "New Zealand v Egypt",                          "G", "Group Stage",    "BC Place",                    "Vancouver"),
    (41, "22-Jun-26", "20:00", "20:00", "Norway v Senegal",                             "I", "Group Stage",    "MetLife Stadium",             "New York/New Jersey"),
    (42, "22-Jun-26", "17:00", "17:00", "France v Iraq",                                "I", "Group Stage",    "Lincoln Financial Field",     "Philadelphia"),
    (43, "22-Jun-26", "13:00", "12:00", "Argentina v Austria",                          "J", "Group Stage",    "AT&T Stadium",                "Dallas"),
    (44, "22-Jun-26", "23:00", "20:00", "Jordan v Algeria",                             "J", "Group Stage",    "Levi's Stadium",              "San Francisco Bay Area"),
    (45, "23-Jun-26", "16:00", "16:00", "England v Ghana",                              "L", "Group Stage",    "Gillette Stadium",            "Boston"),
    (46, "23-Jun-26", "19:00", "19:00", "Panama v Croatia",                             "L", "Group Stage",    "BMO Field",                   "Toronto"),
    (47, "23-Jun-26", "13:00", "12:00", "Portugal v Uzbekistan",                        "K", "Group Stage",    "NRG Stadium",                 "Houston"),
    (48, "23-Jun-26", "22:00", "20:00", "Colombia v Congo DR",                          "K", "Group Stage",    "Estadio Akron",               "Guadalajara"),
    (49, "24-Jun-26", "18:00", "18:00", "Scotland v Brazil",                            "C", "Group Stage",    "Hard Rock Stadium",           "Miami"),
    (50, "24-Jun-26", "18:00", "18:00", "Morocco v Haiti",                              "C", "Group Stage",    "Mercedes-Benz Stadium",       "Atlanta"),
    (51, "24-Jun-26", "15:00", "12:00", "Switzerland v Canada",                         "B", "Group Stage",    "BC Place",                    "Vancouver"),
    (52, "24-Jun-26", "15:00", "12:00", "Bosnia and Herzegovina v Qatar",               "B", "Group Stage",    "Lumen Field",                 "Seattle"),
    (53, "24-Jun-26", "21:00", "19:00", "Czechia v Mexico",                             "A", "Group Stage",    "Estadio Azteca",              "Mexico City"),
    (54, "24-Jun-26", "21:00", "19:00", "South Africa v South Korea",                   "A", "Group Stage",    "Estadio BBVA",                "Monterrey"),
    (55, "25-Jun-26", "16:00", "16:00", "Curaçao v Ivory Coast",                        "E", "Group Stage",    "Lincoln Financial Field",     "Philadelphia"),
    (56, "25-Jun-26", "16:00", "16:00", "Ecuador v Germany",                            "E", "Group Stage",    "MetLife Stadium",             "New York/New Jersey"),
    (57, "25-Jun-26", "19:00", "18:00", "Japan v Sweden",                               "F", "Group Stage",    "AT&T Stadium",                "Dallas"),
    (58, "25-Jun-26", "19:00", "18:00", "Tunisia v Netherlands",                        "F", "Group Stage",    "Arrowhead Stadium",           "Kansas City"),
    (59, "25-Jun-26", "22:00", "19:00", "Türkiye v USA",                                "D", "Group Stage",    "SoFi Stadium",                "Los Angeles"),
    (60, "25-Jun-26", "22:00", "19:00", "Paraguay v Australia",                         "D", "Group Stage",    "Levi's Stadium",              "San Francisco Bay Area"),
    (61, "26-Jun-26", "15:00", "15:00", "Norway v France",                              "I", "Group Stage",    "Gillette Stadium",            "Boston"),
    (62, "26-Jun-26", "15:00", "15:00", "Senegal v Iraq",                               "I", "Group Stage",    "BMO Field",                   "Toronto"),
    (63, "26-Jun-26", "23:00", "20:00", "Egypt v Iran",                                 "G", "Group Stage",    "Lumen Field",                 "Seattle"),
    (64, "26-Jun-26", "23:00", "20:00", "New Zealand v Belgium",                        "G", "Group Stage",    "BC Place",                    "Vancouver"),
    (65, "26-Jun-26", "20:00", "19:00", "Cape Verde v Saudi Arabia",                    "H", "Group Stage",    "NRG Stadium",                 "Houston"),
    (66, "26-Jun-26", "20:00", "18:00", "Uruguay v Spain",                              "H", "Group Stage",    "Estadio Akron",               "Guadalajara"),
    (67, "27-Jun-26", "17:00", "17:00", "Panama v England",                             "L", "Group Stage",    "MetLife Stadium",             "New York/New Jersey"),
    (68, "27-Jun-26", "17:00", "17:00", "Croatia v Ghana",                              "L", "Group Stage",    "Lincoln Financial Field",     "Philadelphia"),
    (69, "27-Jun-26", "22:00", "21:00", "Algeria v Austria",                            "J", "Group Stage",    "Arrowhead Stadium",           "Kansas City"),
    (70, "27-Jun-26", "22:00", "21:00", "Jordan v Argentina",                           "J", "Group Stage",    "AT&T Stadium",                "Dallas"),
    (71, "27-Jun-26", "19:30", "19:30", "Colombia v Portugal",                          "K", "Group Stage",    "Hard Rock Stadium",           "Miami"),
    (72, "27-Jun-26", "19:30", "19:30", "Congo DR v Uzbekistan",                        "K", "Group Stage",    "Mercedes-Benz Stadium",       "Atlanta"),
    # ── Round of 32 ──────────────────────────────────────────────────────────
    (73, "28-Jun-26", "15:00", "12:00", "Group A Runners Up v Group B Runners Up",      "", "Round of 32",    "SoFi Stadium",                "Los Angeles"),
    (74, "29-Jun-26", "16:30", "16:30", "Group E Winners v Group A/B/C/D/F 3rd Place",  "", "Round of 32",    "Gillette Stadium",            "Boston"),
    (75, "29-Jun-26", "21:00", "19:00", "Group F Winners v Group C Runners Up",         "", "Round of 32",    "Estadio BBVA",                "Monterrey"),
    (76, "29-Jun-26", "13:00", "12:00", "Group C Winners v Group F Runners Up",         "", "Round of 32",    "NRG Stadium",                 "Houston"),
    (77, "30-Jun-26", "17:00", "17:00", "Group I Winners v Group C/D/F/G/H 3rd Place",  "", "Round of 32",    "MetLife Stadium",             "New York/New Jersey"),
    (78, "30-Jun-26", "13:00", "12:00", "Group E Runners Up v Group I Runners Up",      "", "Round of 32",    "AT&T Stadium",                "Dallas"),
    (79, "30-Jun-26", "21:00", "19:00", "Group A Winners v Group C/E/F/H/I 3rd Place",  "", "Round of 32",    "Estadio Azteca",              "Mexico City"),
    (80, "1-Jul-26",  "12:00", "12:00", "Group L Winners v Group E/H/I/J/K 3rd Place",  "", "Round of 32",    "Mercedes-Benz Stadium",       "Atlanta"),
    (81, "1-Jul-26",  "20:00", "17:00", "Group D Winners v Group B/E/F/I/J 3rd Place",  "", "Round of 32",    "Levi's Stadium",              "San Francisco Bay Area"),
    (82, "1-Jul-26",  "16:00", "13:00", "Group G Winners v Group A/E/H/I/J 3rd Place",  "", "Round of 32",    "Lumen Field",                 "Seattle"),
    (83, "2-Jul-26",  "19:00", "19:00", "Group K Runners Up v Group L Runners Up",      "", "Round of 32",    "BMO Field",                   "Toronto"),
    (84, "2-Jul-26",  "15:00", "12:00", "Group H Winners v Group J Runners Up",         "", "Round of 32",    "SoFi Stadium",                "Los Angeles"),
    (85, "2-Jul-26",  "23:00", "20:00", "Group B Winners v Group E/F/G/I/J 3rd Place",  "", "Round of 32",    "BC Place",                    "Vancouver"),
    (86, "3-Jul-26",  "18:00", "18:00", "Group J Winners v Group H Runners Up",         "", "Round of 32",    "Hard Rock Stadium",           "Miami"),
    (87, "3-Jul-26",  "21:30", "20:30", "Group K Winners v Group D/E/I/J/L 3rd Place",  "", "Round of 32",    "Arrowhead Stadium",           "Kansas City"),
    (88, "3-Jul-26",  "14:00", "13:00", "Group D Runners Up v Group G Runners Up",      "", "Round of 32",    "AT&T Stadium",                "Dallas"),
    # ── Round of 16 ──────────────────────────────────────────────────────────
    (89, "4-Jul-26",  "17:00", "17:00", "Match 74 Winner v Match 77 Winner",            "", "Round of 16",    "Lincoln Financial Field",     "Philadelphia"),
    (90, "4-Jul-26",  "13:00", "12:00", "Match 73 Winner v Match 75 Winner",            "", "Round of 16",    "NRG Stadium",                 "Houston"),
    (91, "5-Jul-26",  "16:00", "16:00", "Match 76 Winner v Match 78 Winner",            "", "Round of 16",    "MetLife Stadium",             "New York/New Jersey"),
    (92, "5-Jul-26",  "20:00", "18:00", "Match 79 Winner v Match 80 Winner",            "", "Round of 16",    "Estadio Azteca",              "Mexico City"),
    (93, "6-Jul-26",  "15:00", "14:00", "Match 83 Winner v Match 84 Winner",            "", "Round of 16",    "AT&T Stadium",                "Dallas"),
    (94, "6-Jul-26",  "20:00", "17:00", "Match 81 Winner v Match 82 Winner",            "", "Round of 16",    "Lumen Field",                 "Seattle"),
    (95, "7-Jul-26",  "12:00", "12:00", "Match 86 Winner v Match 88 Winner",            "", "Round of 16",    "Mercedes-Benz Stadium",       "Atlanta"),
    (96, "7-Jul-26",  "16:00", "13:00", "Match 85 Winner v Match 87 Winner",            "", "Round of 16",    "BC Place",                    "Vancouver"),
    # ── Quarter-finals ───────────────────────────────────────────────────────
    (97,  "9-Jul-26",  "16:00", "16:00", "Match 89 Winner v Match 90 Winner",           "", "Quarter-finals", "Gillette Stadium",            "Boston"),
    (98,  "10-Jul-26", "15:00", "12:00", "Match 93 Winner v Match 94 Winner",           "", "Quarter-finals", "SoFi Stadium",                "Los Angeles"),
    (99,  "11-Jul-26", "17:00", "17:00", "Match 91 Winner v Match 92 Winner",           "", "Quarter-finals", "Hard Rock Stadium",           "Miami"),
    (100, "11-Jul-26", "21:00", "20:00", "Match 95 Winner v Match 96 Winner",           "", "Quarter-finals", "Arrowhead Stadium",           "Kansas City"),
    # ── Semi-finals ──────────────────────────────────────────────────────────
    (101, "14-Jul-26", "15:00", "14:00", "Match 97 Winner v Match 98 Winner",           "", "Semi-finals",    "AT&T Stadium",                "Dallas"),
    (102, "15-Jul-26", "15:00", "15:00", "Match 99 Winner v Match 100 Winner",          "", "Semi-finals",    "Mercedes-Benz Stadium",       "Atlanta"),
    # ── Third Place ──────────────────────────────────────────────────────────
    (103, "18-Jul-26", "17:00", "17:00", "Match 101 Loser v Match 102 Loser",           "", "Third Place",    "Hard Rock Stadium",           "Miami"),
    # ── Final ────────────────────────────────────────────────────────────────
    (104, "19-Jul-26", "15:00", "15:00", "Match 101 Winner v Match 102 Winner",         "", "Final",          "MetLife Stadium",             "New York/New Jersey"),
]
