"""
Static profiles for all 48 WC 2026 participants.

fifa_rank         : approximate FIFA ranking, June 2026
coach             : head coach name
wc_appearances    : number of WC appearances including 2026
group_stage_adv   : number of times advanced past group stage (knockout stage reached)
top3              : list of (year, place) — place is 1/2/3
players           : list of (name, position, rating)  rating = 1-99 quality score
"""
from __future__ import annotations

_P = tuple  # (name, pos, rating)


TEAM_PROFILES: dict[str, dict] = {

    # ── Group A ───────────────────────────────────────────────────────────────
    "Mexico": {
        "flag": "🇲🇽", "fifa_rank": 16, "coach": "Javier Aguirre",
        "wc_appearances": 18, "group_stage_adv": 14,
        "top3": [],
        "players": [
            ("Guillermo Ochoa",     "GK",  79),
            ("Jorge Sánchez",       "RB",  77),
            ("César Montes",        "CB",  78),
            ("Johan Vásquez",       "CB",  77),
            ("Gerardo Arteaga",     "LB",  76),
            ("Edson Álvarez",       "CDM", 83),
            ("Héctor Herrera",      "CM",  78),
            ("Hirving Lozano",      "RW",  80),
            ("Uriel Antuna",        "LW",  75),
            ("Raúl Jiménez",        "ST",  80),
            ("Henry Martín",        "ST",  77),
        ],
    },
    "South Africa": {
        "flag": "🇿🇦", "fifa_rank": 41, "coach": "Hugo Broos",
        "wc_appearances": 4, "group_stage_adv": 1,
        "top3": [],
        "players": [
            ("Ronwen Williams",     "GK",  73),
            ("Reeve Frosler",       "RB",  72),
            ("Rushine de Reuck",    "CB",  72),
            ("Siyanda Xulu",        "CB",  71),
            ("Innocent Maela",      "LB",  70),
            ("Teboho Mokoena",      "CM",  75),
            ("Ethan Ntsiba",        "CM",  71),
            ("Themba Zwane",        "CAM", 74),
            ("Bongokuhle Hlongwane","LW",  73),
            ("Percy Tau",           "RW",  77),
            ("Evidence Makgopa",    "ST",  74),
        ],
    },
    "South Korea": {
        "flag": "🇰🇷", "fifa_rank": 22, "coach": "Hong Myung-bo",
        "wc_appearances": 11, "group_stage_adv": 6,
        "top3": [],
        "players": [
            ("Kim Seung-gyu",       "GK",  76),
            ("Kim Moon-hwan",       "RB",  75),
            ("Kim Min-jae",         "CB",  87),
            ("Jung Seung-hyun",     "CB",  74),
            ("Kim Jin-su",          "LB",  74),
            ("Hwang In-beom",       "CM",  78),
            ("Jeong Woo-yeong",     "CM",  77),
            ("Lee Jae-sung",        "CAM", 78),
            ("Hwang Hee-chan",      "LW",  80),
            ("Son Heung-min",       "RW",  88),
            ("Cho Gue-sung",        "ST",  78),
        ],
    },
    "Czechia": {
        "flag": "🇨🇿", "fifa_rank": 39, "coach": "Ivan Hašek",
        "wc_appearances": 10, "group_stage_adv": 5,
        "top3": [(1934, 2), (1962, 2)],  # as Czechoslovakia
        "players": [
            ("Jiří Staněk",         "GK",  78),
            ("Vladimir Coufal",     "RB",  76),
            ("Tomáš Holeš",         "CB",  75),
            ("Jakub Brabec",        "CB",  74),
            ("Jan Bořil",           "LB",  74),
            ("Tomáš Souček",        "CM",  82),
            ("Lukáš Provod",        "CM",  76),
            ("Antonín Barák",       "CAM", 78),
            ("Ondřej Lingr",        "LW",  75),
            ("Lukáš Haraslín",      "RW",  75),
            ("Patrik Schick",       "ST",  82),
        ],
    },

    # ── Group B ───────────────────────────────────────────────────────────────
    "Canada": {
        "flag": "🇨🇦", "fifa_rank": 26, "coach": "Jesse Marsch",
        "wc_appearances": 3, "group_stage_adv": 0,
        "top3": [],
        "players": [
            ("Maxime Crépeau",      "GK",  78),
            ("Richie Laryea",       "RB",  76),
            ("Kamal Miller",        "CB",  77),
            ("Alistair Johnston",   "CB",  76),
            ("Sam Adekugbe",        "LB",  75),
            ("Atiba Hutchinson",    "CDM", 74),
            ("Mark-Anthony Kaye",   "CM",  76),
            ("Jonathan David",      "ST",  85),
            ("Alphonso Davies",     "LW",  87),
            ("Cyle Larin",          "ST",  79),
            ("Tajon Buchanan",      "RW",  79),
        ],
    },
    "Bosnia and Herzegovina": {
        "flag": "🇧🇦", "fifa_rank": 38, "coach": "Sergej Barbarez",
        "wc_appearances": 2, "group_stage_adv": 0,
        "top3": [],
        "players": [
            ("Ibrahim Šehić",       "GK",  74),
            ("Sead Kolašinac",      "LB",  76),
            ("Dario Šimić",         "CB",  73),
            ("Ermin Bičakčić",      "CB",  73),
            ("Amer Gojak",          "CM",  76),
            ("Miralem Pjanić",      "CM",  80),
            ("Edin Džeko",          "ST",  79),
            ("Ermedin Demirović",   "ST",  78),
            ("Amir Hadžiahmetović", "CM",  75),
            ("Anel Ahmedhodžić",    "CB",  77),
            ("Deni Jurić",          "ST",  74),
        ],
    },
    "Switzerland": {
        "flag": "🇨🇭", "fifa_rank": 18, "coach": "Murat Yakin",
        "wc_appearances": 12, "group_stage_adv": 8,
        "top3": [],
        "players": [
            ("Yann Sommer",         "GK",  84),
            ("Silvan Widmer",       "RB",  78),
            ("Manuel Akanji",       "CB",  85),
            ("Fabian Schär",        "CB",  81),
            ("Ricardo Rodríguez",   "LB",  78),
            ("Granit Xhaka",        "CDM", 83),
            ("Remo Freuler",        "CM",  80),
            ("Xherdan Shaqiri",     "RW",  80),
            ("Ruben Vargas",        "LW",  78),
            ("Noah Okafor",         "ST",  80),
            ("Breel Embolo",        "ST",  80),
        ],
    },
    "Qatar": {
        "flag": "🇶🇦", "fifa_rank": 47, "coach": "Carlos Queiroz",
        "wc_appearances": 2, "group_stage_adv": 0,
        "top3": [],
        "players": [
            ("Meshaal Barsham",     "GK",  71),
            ("Pedro Miguel",        "LB",  71),
            ("Boualem Khoukhi",     "CB",  70),
            ("Bassam Al-Rawi",      "CB",  70),
            ("Homam Ahmed",         "RB",  69),
            ("Karim Boudiaf",       "CDM", 72),
            ("Abdulaziz Hatem",     "CM",  72),
            ("Hassan Al-Haydos",    "CAM", 74),
            ("Akram Afif",          "LW",  76),
            ("Almoez Ali",          "ST",  75),
            ("Mohammed Muntari",    "ST",  73),
        ],
    },

    # ── Group C ───────────────────────────────────────────────────────────────
    "Haiti": {
        "flag": "🇭🇹", "fifa_rank": 45, "coach": "Marc Collat",
        "wc_appearances": 2, "group_stage_adv": 0,
        "top3": [],
        "players": [
            ("Josué Duverger",      "GK",  68),
            ("Andrew Jean-Baptiste","CB",  70),
            ("Mechack Jérôme",      "CB",  69),
            ("Duckens Nazon",       "RW",  72),
            ("Wilde-Donald Guerrier","CM", 70),
            ("Frantzdy Pierrot",    "ST",  72),
            ("Steeven Saba",        "LW",  70),
            ("Derrick Étienne",     "CM",  71),
            ("Winel Coiffic",       "LB",  67),
            ("Lionel Ainmon",       "RB",  67),
            ("Ronaldo Damus",       "ST",  72),
        ],
    },
    "Scotland": {
        "flag": "🏴󠁧󠁢󠁳󠁣󠁴󠁿", "fifa_rank": 30, "coach": "Steve Clarke",
        "wc_appearances": 9, "group_stage_adv": 1,
        "top3": [],
        "players": [
            ("Craig Gordon",        "GK",  76),
            ("Aaron Hickey",        "RB",  79),
            ("Grant Hanley",        "CB",  75),
            ("Liam Cooper",         "CB",  74),
            ("Andrew Robertson",    "LB",  84),
            ("Billy Gilmour",       "CM",  79),
            ("John McGinn",         "CM",  80),
            ("Callum McGregor",     "CDM", 78),
            ("Ryan Christie",       "CAM", 77),
            ("Scott McKenna",       "CB",  75),
            ("Lawrence Shankland",  "ST",  78),
        ],
    },
    "Brazil": {
        "flag": "🇧🇷", "fifa_rank": 5, "coach": "Dorival Júnior",
        "wc_appearances": 22, "group_stage_adv": 18,
        "top3": [(1938, 3), (1950, 2), (1958, 1), (1962, 1), (1970, 1), (1978, 3), (1994, 1), (1998, 2), (2002, 1)],
        "players": [
            ("Alisson",             "GK",  89),
            ("Éder Militão",        "RB",  86),
            ("Marquinhos",          "CB",  86),
            ("Gabriel Magalhães",   "CB",  83),
            ("Wendell",             "LB",  79),
            ("Casemiro",            "CDM", 83),
            ("Bruno Guimarães",     "CM",  85),
            ("Lucas Paquetá",       "CAM", 84),
            ("Rodrygo",             "RW",  85),
            ("Vinícius Jr",         "LW",  91),
            ("Endrick",             "ST",  83),
        ],
    },
    "Morocco": {
        "flag": "🇲🇦", "fifa_rank": 11, "coach": "Walid Regragui",
        "wc_appearances": 7, "group_stage_adv": 3,
        "top3": [],
        "players": [
            ("Yassine Bounou",      "GK",  85),
            ("Achraf Hakimi",       "RB",  87),
            ("Romain Saïss",        "CB",  79),
            ("Nayef Aguerd",        "CB",  81),
            ("Noussair Mazraoui",   "LB",  82),
            ("Sofyan Amrabat",      "CDM", 82),
            ("Azzedine Ounahi",     "CM",  79),
            ("Selim Amallah",       "CM",  76),
            ("Hakim Ziyech",        "CAM", 82),
            ("Sofiane Boufal",      "LW",  79),
            ("Youssef En-Nesyri",   "ST",  81),
        ],
    },

    # ── Group D ───────────────────────────────────────────────────────────────
    "USA": {
        "flag": "🇺🇸", "fifa_rank": 13, "coach": "Mauricio Pochettino",
        "wc_appearances": 12, "group_stage_adv": 6,
        "top3": [(1930, 3)],
        "players": [
            ("Matt Turner",         "GK",  78),
            ("Sergino Dest",        "RB",  79),
            ("Chris Richards",      "CB",  78),
            ("Tim Ream",            "CB",  76),
            ("Antonee Robinson",    "LB",  81),
            ("Tyler Adams",         "CDM", 82),
            ("Weston McKennie",     "CM",  80),
            ("Yunus Musah",         "CM",  80),
            ("Christian Pulisic",   "CAM", 84),
            ("Timothy Weah",        "RW",  78),
            ("Folarin Balogun",     "ST",  79),
        ],
    },
    "Paraguay": {
        "flag": "🇵🇾", "fifa_rank": 33, "coach": "Gustavo Alfaro",
        "wc_appearances": 9, "group_stage_adv": 5,
        "top3": [],
        "players": [
            ("Antony Silva",        "GK",  74),
            ("Robert Rojas",        "RB",  77),
            ("Gustavo Gómez",       "CB",  79),
            ("Fabián Balbuena",     "CB",  76),
            ("Blas Riveros",        "LB",  75),
            ("Andrés Cubas",        "CDM", 76),
            ("Miguel Almirón",      "CM",  81),
            ("Ángel Romero",        "RW",  77),
            ("Alejandro Romero",    "LW",  74),
            ("Gabriel Ávalos",      "ST",  75),
            ("Carlos González",     "ST",  74),
        ],
    },
    "Australia": {
        "flag": "🇦🇺", "fifa_rank": 23, "coach": "Tony Popovic",
        "wc_appearances": 6, "group_stage_adv": 3,
        "top3": [],
        "players": [
            ("Mathew Ryan",         "GK",  79),
            ("Nathaniel Atkinson",  "RB",  75),
            ("Harry Souttar",       "CB",  80),
            ("Kye Rowles",          "CB",  76),
            ("Aziz Behich",         "LB",  75),
            ("Jackson Irvine",      "CM",  78),
            ("Keanu Baccus",        "CM",  75),
            ("Riley McGree",        "CAM", 78),
            ("Mathew Leckie",       "RW",  77),
            ("Martin Boyle",        "LW",  76),
            ("Mitchell Duke",       "ST",  74),
        ],
    },
    "Türkiye": {
        "flag": "🇹🇷", "fifa_rank": 21, "coach": "Vincenzo Montella",
        "wc_appearances": 5, "group_stage_adv": 2,
        "top3": [(2002, 3)],
        "players": [
            ("Uğurcan Çakır",       "GK",  80),
            ("Zeki Çelik",          "RB",  79),
            ("Merih Demiral",       "CB",  82),
            ("Samet Akaydin",       "CB",  77),
            ("Ferdi Kadıoğlu",      "LB",  80),
            ("Hakan Çalhanoğlu",    "CDM", 85),
            ("Kaan Ayhan",          "CM",  77),
            ("Arda Güler",          "CAM", 83),
            ("Kerem Aktürkoğlu",    "LW",  79),
            ("Çağlar Söyüncü",      "CB",  79),
            ("Baris Yilmaz",        "ST",  78),
        ],
    },

    # ── Group E ───────────────────────────────────────────────────────────────
    "Ivory Coast": {
        "flag": "🇨🇮", "fifa_rank": 29, "coach": "Emerse Faé",
        "wc_appearances": 4, "group_stage_adv": 0,
        "top3": [],
        "players": [
            ("Yahia Fofana",        "GK",  78),
            ("Serge Aurier",        "RB",  77),
            ("Odilon Kossounou",    "CB",  79),
            ("Wilfried Singo",      "RB",  79),
            ("Ghislain Konan",      "LB",  75),
            ("Franck Kessié",       "CDM", 83),
            ("Jean Michaël Seri",   "CM",  77),
            ("Sébastien Haller",    "ST",  80),
            ("Nicolas Pépé",        "RW",  79),
            ("Simon Adingra",       "LW",  79),
            ("Oumar Diakité",       "CAM", 76),
        ],
    },
    "Ecuador": {
        "flag": "🇪🇨", "fifa_rank": 21, "coach": "Sebastián Beccacece",
        "wc_appearances": 5, "group_stage_adv": 2,
        "top3": [],
        "players": [
            ("Hernán Galíndez",     "GK",  75),
            ("Ángelo Preciado",     "RB",  77),
            ("Félix Torres",        "CB",  79),
            ("Piero Hincapié",      "CB",  81),
            ("Pervis Estupiñán",    "LB",  82),
            ("Carlos Gruezo",       "CDM", 76),
            ("Moisés Caicedo",      "CM",  85),
            ("Gonzalo Plata",       "RW",  77),
            ("Jeremy Sarmiento",    "LW",  76),
            ("Énner Valencia",      "ST",  80),
            ("Kevin Rodríguez",     "CAM", 75),
        ],
    },
    "Germany": {
        "flag": "🇩🇪", "fifa_rank": 9, "coach": "Julian Nagelsmann",
        "wc_appearances": 21, "group_stage_adv": 17,
        "top3": [
            (1934, 3), (1954, 1), (1966, 2), (1970, 3), (1974, 1),
            (1982, 2), (1986, 2), (1990, 1), (2002, 2), (2006, 3),
            (2010, 3), (2014, 1),
        ],
        "players": [
            ("Marc-André ter Stegen","GK", 87),
            ("Joshua Kimmich",      "RB",  88),
            ("Antonio Rüdiger",     "CB",  86),
            ("Jonathan Tah",        "CB",  82),
            ("Maximilian Mittelstädt","LB",79),
            ("Aleksandar Pavlović", "CDM", 79),
            ("Ilkay Gündogan",      "CM",  83),
            ("Florian Wirtz",       "CAM", 88),
            ("Leroy Sané",          "RW",  84),
            ("Jamal Musiala",       "LW",  87),
            ("Kai Havertz",         "ST",  84),
        ],
    },
    "Curaçao": {
        "flag": "🇨🇼", "fifa_rank": 48, "coach": "Remko Bicentini",
        "wc_appearances": 1, "group_stage_adv": 0,
        "top3": [],
        "players": [
            ("Eloy Room",           "GK",  74),
            ("Cuco Martina",        "RB",  70),
            ("Jurickson Profar",    "CM",  72),
            ("Leandro Bacuna",      "CM",  73),
            ("Darryl Lachman",      "CB",  70),
            ("Rangelo Janga",       "LW",  70),
            ("Gevaro Nepomuceno",   "RW",  70),
            ("Jarchinio Antonia",   "CAM", 71),
            ("Quentin Laméris",     "ST",  70),
            ("Gaston Celina",       "CAM", 72),
            ("Ferdy Druijf",        "ST",  70),
        ],
    },

    # ── Group F ───────────────────────────────────────────────────────────────
    "Netherlands": {
        "flag": "🇳🇱", "fifa_rank": 7, "coach": "Ronald Koeman",
        "wc_appearances": 12, "group_stage_adv": 9,
        "top3": [(1974, 2), (1978, 2), (2010, 2), (2014, 3)],
        "players": [
            ("Bart Verbruggen",     "GK",  81),
            ("Denzel Dumfries",     "RB",  83),
            ("Virgil van Dijk",     "CB",  88),
            ("Stefan de Vrij",      "CB",  82),
            ("Nathan Aké",          "LB",  82),
            ("Jerdy Schouten",      "CDM", 78),
            ("Frenkie de Jong",     "CM",  86),
            ("Teun Koopmeiners",    "CM",  84),
            ("Donyell Malen",       "RW",  80),
            ("Cody Gakpo",          "LW",  83),
            ("Memphis Depay",       "ST",  82),
        ],
    },
    "Japan": {
        "flag": "🇯🇵", "fifa_rank": 14, "coach": "Hajime Moriyasu",
        "wc_appearances": 8, "group_stage_adv": 4,
        "top3": [],
        "players": [
            ("Shuichi Gonda",       "GK",  76),
            ("Hiroki Sakai",        "RB",  77),
            ("Ko Itakura",          "CB",  79),
            ("Shogo Taniguchi",     "CB",  77),
            ("Yuto Nagatomo",       "LB",  75),
            ("Wataru Endo",         "CDM", 80),
            ("Hidemasa Morita",     "CM",  78),
            ("Daichi Kamada",       "CAM", 81),
            ("Takefusa Kubo",       "RW",  83),
            ("Kaoru Mitoma",        "LW",  83),
            ("Ayase Ueda",          "ST",  78),
        ],
    },
    "Sweden": {
        "flag": "🇸🇪", "fifa_rank": 26, "coach": "Jon Dahl Tomasson",
        "wc_appearances": 13, "group_stage_adv": 8,
        "top3": [(1950, 3), (1958, 2), (1994, 3)],
        "players": [
            ("Robin Olsen",         "GK",  77),
            ("Mikael Lustig",       "RB",  72),
            ("Victor Lindelöf",     "CB",  81),
            ("Isak Bergmann Jóhannesson","CB",75),
            ("Ludwig Augustinsson", "LB",  76),
            ("Albin Ekdal",         "CDM", 76),
            ("Dejan Kulusevski",    "CM",  84),
            ("Viktor Claesson",     "CM",  77),
            ("Jesper Karlsson",     "LW",  79),
            ("Emil Forsberg",       "CAM", 80),
            ("Alexander Isak",      "ST",  85),
        ],
    },
    "Tunisia": {
        "flag": "🇹🇳", "fifa_rank": 40, "coach": "Jalel Kadri",
        "wc_appearances": 7, "group_stage_adv": 1,
        "top3": [],
        "players": [
            ("Aymen Dahmen",        "GK",  74),
            ("Mohamed Dräger",      "RB",  74),
            ("Montassar Talbi",     "CB",  75),
            ("Yassine Meriah",      "CB",  74),
            ("Ali Maâloul",         "LB",  77),
            ("Aïssa Laïdouni",      "CDM", 76),
            ("Ellyes Skhiri",       "CM",  78),
            ("Khaled Kadri",        "CM",  74),
            ("Naïm Sliti",          "RW",  75),
            ("Wahbi Khazri",        "CAM", 77),
            ("Seifeddine Jaziri",   "ST",  75),
        ],
    },

    # ── Group G ───────────────────────────────────────────────────────────────
    "Iran": {
        "flag": "🇮🇷", "fifa_rank": 27, "coach": "Amir Ghalenoei",
        "wc_appearances": 7, "group_stage_adv": 0,
        "top3": [],
        "players": [
            ("Alireza Beiranvand",  "GK",  78),
            ("Ehsan Hajsafi",       "LB",  75),
            ("Majid Hosseini",      "CB",  75),
            ("Shoja Khalilzadeh",   "CB",  74),
            ("Sadegh Moharrami",    "RB",  73),
            ("Saeid Ezatolahi",     "CDM", 77),
            ("Ahmad Nourollahi",    "CM",  75),
            ("Ali Gholizadeh",      "LW",  76),
            ("Milad Sarlak",        "RW",  74),
            ("Sardar Azmoun",       "ST",  81),
            ("Mehdi Taremi",        "ST",  82),
        ],
    },
    "New Zealand": {
        "flag": "🇳🇿", "fifa_rank": 42, "coach": "Darren Bazeley",
        "wc_appearances": 3, "group_stage_adv": 0,
        "top3": [],
        "players": [
            ("Oli Sail",            "GK",  73),
            ("Liberato Cacace",     "LB",  76),
            ("Winston Reid",        "CB",  73),
            ("Michael Boxall",      "CB",  73),
            ("Nikita Rukavytsya",   "RW",  71),
            ("Clayton Lewis",       "CM",  73),
            ("Marco Rojas",         "LW",  72),
            ("Elijah Just",         "CM",  72),
            ("Tim Payne",           "RB",  70),
            ("Marko Simonović",     "ST",  73),
            ("Chris Wood",          "ST",  78),
        ],
    },
    "Belgium": {
        "flag": "🇧🇪", "fifa_rank": 8, "coach": "Domenico Tedesco",
        "wc_appearances": 14, "group_stage_adv": 9,
        "top3": [(2018, 3)],
        "players": [
            ("Koen Casteels",       "GK",  83),
            ("Thomas Castagne",     "RB",  80),
            ("Wout Faes",           "CB",  78),
            ("Jan Vertonghen",      "CB",  79),
            ("Arthur Theate",       "LB",  79),
            ("Amadou Onana",        "CDM", 81),
            ("Youri Tielemans",     "CM",  81),
            ("Kevin De Bruyne",     "CAM", 90),
            ("Dodi Lukebakio",      "RW",  79),
            ("Jérémy Doku",         "LW",  82),
            ("Romelu Lukaku",       "ST",  84),
        ],
    },
    "Egypt": {
        "flag": "🇪🇬", "fifa_rank": 32, "coach": "Ihab Galal",
        "wc_appearances": 4, "group_stage_adv": 1,
        "top3": [],
        "players": [
            ("Mohamed El-Shenawy",  "GK",  76),
            ("Ahmed Fattouh",       "RB",  73),
            ("Ahmed Hegazy",        "CB",  77),
            ("Omar Gaber",          "CB",  73),
            ("Mohamed Abdel-Shafi", "LB",  72),
            ("Tarek Hamed",         "CDM", 75),
            ("Emam Ashour",         "CM",  74),
            ("Mohamed Salah",       "RW",  91),
            ("Trezeguet",           "LW",  78),
            ("Omar Marmoush",       "CAM", 83),
            ("Mostafa Mohamed",     "ST",  78),
        ],
    },

    # ── Group H ───────────────────────────────────────────────────────────────
    "Saudi Arabia": {
        "flag": "🇸🇦", "fifa_rank": 37, "coach": "Hervé Renard",
        "wc_appearances": 7, "group_stage_adv": 2,
        "top3": [],
        "players": [
            ("Mohammed Al-Owais",   "GK",  77),
            ("Sultan Al-Ghanam",    "RB",  72),
            ("Ali Al-Bulaihi",      "CB",  74),
            ("Abdulelah Al-Amri",   "CB",  73),
            ("Yasser Al-Shahrani",  "LB",  74),
            ("Mohamed Kanno",       "CDM", 75),
            ("Sami Al-Najei",       "CM",  73),
            ("Saleh Al-Shehri",     "LW",  75),
            ("Mohammed Al-Burayk",  "LB",  73),
            ("Salem Al-Dawsari",    "RW",  79),
            ("Firas Al-Buraikan",   "ST",  77),
        ],
    },
    "Uruguay": {
        "flag": "🇺🇾", "fifa_rank": 10, "coach": "Marcelo Bielsa",
        "wc_appearances": 14, "group_stage_adv": 10,
        "top3": [(1930, 1), (1950, 1)],
        "players": [
            ("Sergio Rochet",       "GK",  79),
            ("Nahitan Nández",      "RB",  79),
            ("José María Giménez",  "CB",  83),
            ("Ronald Araújo",       "CB",  85),
            ("Mathías Olivera",     "LB",  80),
            ("Federico Valverde",   "CM",  87),
            ("Manuel Ugarte",       "CDM", 83),
            ("Rodrigo Bentancur",   "CM",  82),
            ("De Arrascaeta",       "CAM", 83),
            ("Darwin Núñez",        "ST",  84),
            ("Facundo Torres",      "LW",  78),
        ],
    },
    "Cape Verde": {
        "flag": "🇨🇻", "fifa_rank": 43, "coach": "Pedro Brito",
        "wc_appearances": 1, "group_stage_adv": 0,
        "top3": [],
        "players": [
            ("Vozinha",             "GK",  72),
            ("Ryan Mendes",         "RW",  72),
            ("Stopira",             "CB",  73),
            ("Roberto",             "CB",  71),
            ("Diney",               "LB",  70),
            ("Garry Rodrigues",     "LW",  74),
            ("Jamiro Monteiro",     "CM",  73),
            ("Dylan Tavares",       "CM",  71),
            ("Steven Fortes",       "RB",  70),
            ("Kenny Rocha",         "CM",  72),
            ("Djaniny",             "ST",  74),
        ],
    },
    "Spain": {
        "flag": "🇪🇸", "fifa_rank": 3, "coach": "Luis de la Fuente",
        "wc_appearances": 16, "group_stage_adv": 11,
        "top3": [(2010, 1)],
        "players": [
            ("Unai Simón",          "GK",  84),
            ("Dani Carvajal",       "RB",  85),
            ("Aymeric Laporte",     "CB",  83),
            ("Robin Le Normand",    "CB",  81),
            ("Marc Cucurella",      "LB",  81),
            ("Martín Zubimendi",    "CDM", 82),
            ("Pedri",               "CM",  87),
            ("Dani Olmo",           "CAM", 83),
            ("Lamine Yamal",        "RW",  89),
            ("Nico Williams",       "LW",  85),
            ("Álvaro Morata",       "ST",  81),
        ],
    },

    # ── Group I ───────────────────────────────────────────────────────────────
    "France": {
        "flag": "🇫🇷", "fifa_rank": 2, "coach": "Didier Deschamps",
        "wc_appearances": 16, "group_stage_adv": 12,
        "top3": [(1958, 3), (1986, 3), (1998, 1), (2018, 1), (2022, 2)],
        "players": [
            ("Mike Maignan",        "GK",  88),
            ("Jules Koundé",        "RB",  86),
            ("Dayot Upamecano",     "CB",  84),
            ("William Saliba",      "CB",  86),
            ("Théo Hernández",      "LB",  85),
            ("Aurélien Tchouaméni", "CDM", 85),
            ("Eduardo Camavinga",   "CM",  84),
            ("Antoine Griezmann",   "CAM", 86),
            ("Ousmane Dembélé",     "RW",  84),
            ("Kylian Mbappé",       "LW",  93),
            ("Marcus Thuram",       "ST",  83),
        ],
    },
    "Senegal": {
        "flag": "🇸🇳", "fifa_rank": 20, "coach": "Aliou Cissé",
        "wc_appearances": 4, "group_stage_adv": 2,
        "top3": [],
        "players": [
            ("Édouard Mendy",       "GK",  84),
            ("Bouna Sarr",          "RB",  74),
            ("Abdou Diallo",        "CB",  79),
            ("Kalidou Koulibaly",   "CB",  83),
            ("Formose Mendy",       "LB",  74),
            ("Idrissa Gueye",       "CDM", 79),
            ("Cheikhou Kouyaté",    "CM",  76),
            ("Nampalys Mendy",      "CM",  75),
            ("Sadio Mané",          "LW",  86),
            ("Ismaïla Sarr",        "RW",  80),
            ("Nicolas Jackson",     "ST",  80),
        ],
    },
    "Iraq": {
        "flag": "🇮🇶", "fifa_rank": 36, "coach": "Jesús Casas",
        "wc_appearances": 2, "group_stage_adv": 0,
        "top3": [],
        "players": [
            ("Jalal Hassan",        "GK",  71),
            ("Ali Adnan",           "LB",  74),
            ("Hossam Ali",          "CB",  70),
            ("Saman Shaker",        "CB",  70),
            ("Ahmed Ibrahim",       "RB",  69),
            ("Safaa Hadi",          "CM",  71),
            ("Hussein Ali",         "CDM", 70),
            ("Mohanad Ali",         "RW",  73),
            ("Amjad Atwan",         "LW",  71),
            ("Amir Al-Ammari",      "CAM", 72),
            ("Aymen Hussein",       "ST",  74),
        ],
    },
    "Norway": {
        "flag": "🇳🇴", "fifa_rank": 25, "coach": "Ståle Solbakken",
        "wc_appearances": 4, "group_stage_adv": 2,
        "top3": [],
        "players": [
            ("Ørjan Nyland",        "GK",  77),
            ("Kristoffer Ajer",     "CB",  79),
            ("Andreas Hanche-Olsen","CB",  76),
            ("Birger Meling",       "LB",  76),
            ("Julian Ryerson",      "RB",  76),
            ("Patrick Berg",        "CDM", 77),
            ("Martin Ødegaard",     "CAM", 88),
            ("Sander Berge",        "CM",  79),
            ("Antonio Nusa",        "RW",  80),
            ("Mohamed Elyounoussi","LW",   77),
            ("Erling Haaland",      "ST",  94),
        ],
    },

    # ── Group J ───────────────────────────────────────────────────────────────
    "Argentina": {
        "flag": "🇦🇷", "fifa_rank": 1, "coach": "Lionel Scaloni",
        "wc_appearances": 19, "group_stage_adv": 15,
        "top3": [(1930, 2), (1978, 1), (1986, 1), (1990, 2), (2014, 2), (2022, 1)],
        "players": [
            ("Emiliano Martínez",   "GK",  90),
            ("Nahuel Molina",       "RB",  82),
            ("Cristian Romero",     "CB",  86),
            ("Nicolás Otamendi",    "CB",  81),
            ("Nicolás Tagliafico",  "LB",  79),
            ("Rodrigo De Paul",     "CM",  84),
            ("Leandro Paredes",     "CDM", 80),
            ("Alexis Mac Allister", "CM",  85),
            ("Lionel Messi",        "RW",  90),
            ("Julián Álvarez",      "LW",  85),
            ("Lautaro Martínez",    "ST",  87),
        ],
    },
    "Algeria": {
        "flag": "🇩🇿", "fifa_rank": 28, "coach": "Vladimir Petković",
        "wc_appearances": 5, "group_stage_adv": 2,
        "top3": [],
        "players": [
            ("Raïs M'Bolhi",        "GK",  74),
            ("Youcef Atal",         "RB",  79),
            ("Djamel Benlamri",     "CB",  74),
            ("Ramy Bensebaïni",     "LB",  80),
            ("Aïssa Mandi",         "CB",  76),
            ("Nabil Bentaleb",      "CDM", 77),
            ("Sofiane Feghouli",    "RW",  77),
            ("Islam Slimani",       "ST",  77),
            ("Yacine Brahimi",      "LW",  78),
            ("Houssem Aouar",       "CAM", 79),
            ("Riyad Mahrez",        "RW",  83),
        ],
    },
    "Austria": {
        "flag": "🇦🇹", "fifa_rank": 17, "coach": "Ralf Rangnick",
        "wc_appearances": 8, "group_stage_adv": 3,
        "top3": [(1954, 3)],
        "players": [
            ("Patrick Pentz",       "GK",  77),
            ("Stefan Posch",        "RB",  77),
            ("Maximilian Wöber",    "CB",  79),
            ("Kevin Danso",         "CB",  81),
            ("Philipp Mwene",       "LB",  75),
            ("Nicolas Seiwald",     "CDM", 78),
            ("Florian Grillitsch",  "CM",  77),
            ("Konrad Laimer",       "CM",  82),
            ("Christoph Baumgartner","CAM",80),
            ("Marcel Sabitzer",     "RW",  81),
            ("Michael Gregoritsch", "ST",  78),
        ],
    },
    "Jordan": {
        "flag": "🇯🇴", "fifa_rank": 44, "coach": "Hussam Abu Ali",
        "wc_appearances": 1, "group_stage_adv": 0,
        "top3": [],
        "players": [
            ("Amer Shafi",          "GK",  71),
            ("Badr Al-Mutasem",     "RB",  69),
            ("Yazan Al-Naimat",     "CB",  70),
            ("Abdallah Nasib",      "CB",  68),
            ("Ehsan Haddad",        "LB",  68),
            ("Mohammad Abu Zema",   "CDM", 69),
            ("Hassan Al-Rawabdeh",  "CM",  70),
            ("Musa Al-Tamari",      "RW",  73),
            ("Yazan Al-Arab",       "LW",  70),
            ("Hamza Al-Dardour",    "ST",  72),
            ("Baha Faisal",         "CAM", 69),
        ],
    },

    # ── Group K ───────────────────────────────────────────────────────────────
    "Portugal": {
        "flag": "🇵🇹", "fifa_rank": 6, "coach": "Roberto Martínez",
        "wc_appearances": 9, "group_stage_adv": 7,
        "top3": [(1966, 3)],
        "players": [
            ("Rui Patrício",        "GK",  82),
            ("João Cancelo",        "RB",  85),
            ("Rúben Dias",          "CB",  88),
            ("Gonçalo Inácio",      "CB",  82),
            ("Nuno Mendes",         "LB",  84),
            ("Danilo Pereira",      "CDM", 79),
            ("Vitinha",             "CM",  83),
            ("Bruno Fernandes",     "CAM", 86),
            ("Bernardo Silva",      "RW",  87),
            ("Rafael Leão",         "LW",  84),
            ("Gonçalo Ramos",       "ST",  82),
        ],
    },
    "Congo DR": {
        "flag": "🇨🇩", "fifa_rank": 35, "coach": "Sébastien Desabre",
        "wc_appearances": 2, "group_stage_adv": 1,
        "top3": [],
        "players": [
            ("Joël Kiassumbua",     "GK",  72),
            ("Chancel Mbemba",      "CB",  78),
            ("Cédric Bakambu",      "ST",  76),
            ("Yannick Bolasie",     "RW",  74),
            ("Dénis Zakaria",       "CM",  78),
            ("Neeskens Kebano",     "CAM", 75),
            ("Théo Bongonda",       "LW",  75),
            ("Merveille Bope",      "CM",  73),
            ("Emmanuel Lebo",       "CB",  71),
            ("Silas Wamangituka",   "RW",  74),
            ("Arthur Masuaku",      "LB",  74),
        ],
    },
    "Uzbekistan": {
        "flag": "🇺🇿", "fifa_rank": 46, "coach": "Srecko Katanec",
        "wc_appearances": 1, "group_stage_adv": 0,
        "top3": [],
        "players": [
            ("Eldorbek Suyunov",    "GK",  69),
            ("Sherzod Nasrullayev","RB",   68),
            ("Sanjar Tursunov",     "CB",  69),
            ("Khusan Ergashev",     "CB",  68),
            ("Ulugbek Rashidov",    "LB",  67),
            ("Jasur Yakhshiboev",   "CM",  70),
            ("Otabek Shukurov",     "CDM", 70),
            ("Eldor Shomurodov",    "ST",  76),
            ("Jaloliddin Masharipov","RW", 73),
            ("Bobir Abdixoliqov",   "LW",  70),
            ("Dostonbek Khamdamov","CAM",  69),
        ],
    },
    "Colombia": {
        "flag": "🇨🇴", "fifa_rank": 12, "coach": "Néstor Lorenzo",
        "wc_appearances": 7, "group_stage_adv": 4,
        "top3": [],
        "players": [
            ("David Ospina",        "GK",  82),
            ("Daniel Muñoz",        "RB",  79),
            ("Yerry Mina",          "CB",  80),
            ("Dávinson Sánchez",    "CB",  81),
            ("Johan Mojica",        "LB",  78),
            ("Wilmar Barrios",      "CDM", 78),
            ("Mateus Uribe",        "CM",  76),
            ("James Rodríguez",     "CAM", 82),
            ("Luis Díaz",           "LW",  86),
            ("Juan Cuadrado",       "RW",  79),
            ("Rafael Santos Borré", "ST",  78),
        ],
    },

    # ── Group L ───────────────────────────────────────────────────────────────
    "Ghana": {
        "flag": "🇬🇭", "fifa_rank": 31, "coach": "Otto Addo",
        "wc_appearances": 5, "group_stage_adv": 2,
        "top3": [],
        "players": [
            ("Lawrence Ati-Zigi",   "GK",  76),
            ("Tariqe Fosu",         "RB",  73),
            ("Daniel Amartey",      "CB",  77),
            ("Alexander Djiku",     "CB",  77),
            ("Baba Rahman",         "LB",  75),
            ("Thomas Partey",       "CDM", 84),
            ("Mohammed Kudus",      "CM",  83),
            ("Antoine Semenyo",     "RW",  77),
            ("Kamaldeen Sulemana",  "LW",  78),
            ("Jordan Ayew",         "CAM", 77),
            ("Felix Afena-Gyan",    "ST",  76),
        ],
    },
    "Panama": {
        "flag": "🇵🇦", "fifa_rank": 34, "coach": "Thomas Christiansen",
        "wc_appearances": 3, "group_stage_adv": 0,
        "top3": [],
        "players": [
            ("Luis Mejía",          "GK",  73),
            ("Michael Murillo",     "RB",  75),
            ("Harold Cummings",     "CB",  74),
            ("Fidel Escobar",       "CB",  73),
            ("Eric Davis",          "LB",  72),
            ("Aníbal Godoy",        "CDM", 75),
            ("Alberto Quintero",    "LW",  73),
            ("Édgar Bárcenas",      "RW",  74),
            ("Adalberto Carrasquilla","CM",75),
            ("Cristian Martínez",   "CAM", 73),
            ("Rolando Blackburn",   "ST",  74),
        ],
    },
    "England": {
        "flag": "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "fifa_rank": 4, "coach": "Thomas Tuchel",
        "wc_appearances": 17, "group_stage_adv": 10,
        "top3": [(1966, 1)],
        "players": [
            ("Jordan Pickford",     "GK",  84),
            ("Trent Alexander-Arnold","RB",86),
            ("John Stones",         "CB",  83),
            ("Marc Guéhi",          "CB",  82),
            ("Luke Shaw",           "LB",  82),
            ("Declan Rice",         "CDM", 87),
            ("Jude Bellingham",     "CM",  91),
            ("Phil Foden",          "CAM", 88),
            ("Bukayo Saka",         "RW",  88),
            ("Marcus Rashford",     "LW",  83),
            ("Harry Kane",          "ST",  90),
        ],
    },
    "Croatia": {
        "flag": "🇭🇷", "fifa_rank": 15, "coach": "Zlatko Dalić",
        "wc_appearances": 8, "group_stage_adv": 5,
        "top3": [(1998, 3), (2018, 2)],
        "players": [
            ("Dominik Livaković",   "GK",  83),
            ("Josip Juranović",     "RB",  79),
            ("Joško Gvardiol",      "CB",  86),
            ("Duje Ćaleta-Car",     "CB",  79),
            ("Borna Sosa",          "LB",  78),
            ("Marcelo Brozović",    "CDM", 83),
            ("Mateo Kovačić",       "CM",  84),
            ("Luka Modrić",         "CM",  87),
            ("Ivan Perišić",        "LW",  82),
            ("Nikola Vlašić",       "CAM", 79),
            ("Andrej Kramarić",     "ST",  82),
        ],
    },
}

# ── WC 2026 group assignment (derived from config/teams.json order) ──────────
TEAM_GROUP: dict[str, str] = {
    "Mexico": "A", "South Africa": "A", "South Korea": "A", "Czechia": "A",
    "Canada": "B", "Bosnia and Herzegovina": "B", "Switzerland": "B", "Qatar": "B",
    "Haiti": "C", "Scotland": "C", "Brazil": "C", "Morocco": "C",
    "USA": "D", "Paraguay": "D", "Australia": "D", "Türkiye": "D",
    "Ivory Coast": "E", "Ecuador": "E", "Germany": "E", "Curaçao": "E",
    "Netherlands": "F", "Japan": "F", "Sweden": "F", "Tunisia": "F",
    "Iran": "G", "New Zealand": "G", "Belgium": "G", "Egypt": "G",
    "Saudi Arabia": "H", "Uruguay": "H", "Cape Verde": "H", "Spain": "H",
    "France": "I", "Senegal": "I", "Iraq": "I", "Norway": "I",
    "Argentina": "J", "Algeria": "J", "Austria": "J", "Jordan": "J",
    "Portugal": "K", "Congo DR": "K", "Uzbekistan": "K", "Colombia": "K",
    "Ghana": "L", "Panama": "L", "England": "L", "Croatia": "L",
}
